# Generated by Django 3.2 on 2021-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210416_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='family',
            field=models.CharField(default='Family', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(default='Name', max_length=40, null=True),
        ),
    ]
